# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fakeQQ_loginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(323, 267)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerImageLabel = QtWidgets.QLabel(Form)
        self.headerImageLabel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.headerImageLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.headerImageLabel.setObjectName("headerImageLabel")
        self.verticalLayout.addWidget(self.headerImageLabel)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.userLabel = QtWidgets.QLabel(self.widget_2)
        self.userLabel.setObjectName("userLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userLabel)
        self.userLineEdit = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLineEdit.sizePolicy().hasHeightForWidth())
        self.userLineEdit.setSizePolicy(sizePolicy)
        self.userLineEdit.setInputMask("")
        self.userLineEdit.setObjectName("userLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userLineEdit)
        self.passwdLabel = QtWidgets.QLabel(self.widget_2)
        self.passwdLabel.setObjectName("passwdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwdLabel)
        self.passwdLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.passwdLineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwdLineEdit.setObjectName("passwdLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwdLineEdit)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginBtn = QtWidgets.QPushButton(self.widget)
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.registerBtn = QtWidgets.QPushButton(self.widget)
        self.registerBtn.setObjectName("registerBtn")
        self.horizontalLayout.addWidget(self.registerBtn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.headerImageLabel.setText(_translate("Form", "头像"))
        self.userLabel.setText(_translate("Form", "账户"))
        self.passwdLabel.setText(_translate("Form", "密码"))
        self.loginBtn.setText(_translate("Form", "登陆"))
        self.registerBtn.setText(_translate("Form", "注册"))
