# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fakeQQ_sessionWidet.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sessionWidget(object):
    def setupUi(self, sessionWidget):
        sessionWidget.setObjectName("sessionWidget")
        sessionWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(sessionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(sessionWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.textEdit = QtWidgets.QTextEdit(sessionWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(sessionWidget)
        QtCore.QMetaObject.connectSlotsByName(sessionWidget)

    def retranslateUi(self, sessionWidget):
        _translate = QtCore.QCoreApplication.translate
        sessionWidget.setWindowTitle(_translate("sessionWidget", "Form"))
